FROM centos:latest

MAINTAINER Li Hsin Chang <cc1296@ym.edu.tw>

# OPEN JDK/JRE

RUN yum update -y
RUN yum install -y \
       java-1.8.0-openjdk \
       java-1.8.0-openjdk-devel


RUN yum install -y perl
RUN yum install -y unzip







